### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by mike2307** [v1shwa/contain-twitter#7]
Twitter isn't working any more since about 2-3 days with this extension. I can use twitter only with this extension disabled.

**Comment by v1shwa** [comment]
@mike2307 There are no new releases made for this extension over last 1 year. So, it's very unlikely to break at this time.

Could you please check if any other addon is causing a conflict with Twitter container.

**Comment by cryptomilk** [comment]
tweetdeck.twitter.com works, but twitter.com doesn't.

**Comment by loma-one** [comment]
I can confirm this. 
Firefox Message:


DE: Fehler: Anfrage konnte nicht ausgeführt werden

Beim Laden der Seite https://twitter.com/ wurde gegen das Netzwerkprotokoll verstoßen. Dieser Fehler kann nicht 
behoben werden.

Die Seite, die Sie anzusehen versuchen, kann nicht angezeigt werden, da ein Fehler in der Datenübertragung festgestellt wurde.

    Bitte kontaktieren Sie die Website-Betreiber, um sie über dieses Problem zu verständigen.

---

EN: Error: Request could not be executed

The network protocol was violated when loading the https://twitter.com/ page. This error cannot be corrected.

The page you are trying to view cannot be displayed because a data transmission error has been detected.

    Please contact the website operators to inform them of this problem.

**Comment by mike2307** [comment]
I think that this can be closed. The root cause is the firefox 81 update. Users need to clear all twitter-cached data. Then it's working again (independent with or without the container extension).
See: https://www.reddit.com/r/firefox/comments/j4swws/firefox_8101_for_macos_shows_error_upon_going_to/
